version: "3"
services:
  api_gateway:
    build: .
    ports:
    - "8080:8080"
    environment:
      USER_URL: 192.168.99.100
      USER_PORT: 8081
      RECIPES_URL: 192.168.99.100
      RECIPES_PORT: 8082
      SUPPILERS_URL: 192.168.99.100
      SUPPILERS_PORT: 8083
      FORUMS_URL: 192.168.99.100
      FORUMS_PORT: 8084
      INGREDIENTS_URL: 192.168.99.100
      INGREDIENTS_PORT: 8085
