version: "3"
services:
  users_db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
     POSTGRES_PASSWORD: password


  users_ms:
    build: .
    command: bash -c "sleep 60 && rails db:create && rails db:migrate && rails s -p 8083 -b 0.0.0.0"
    ports:
      - "8083:8083"
    depends_on:
      - users_db
      # - ldap_server
    environment:
      LDAP_HOST: 192.168.99.100
      LDAP_PORT: 389
      LDAP_ADMIN_PASSWORD: admin
